version: '3.8'

services:

  inklinker_backend:
      build: 
        context: ./backend
        dockerfile: Dockerfile
      container_name: inklinker_backend_container
      env_file:
        - .env
      networks:
        - inklinker_network
      volumes:
        - model_data:/app/model

  inklinker_frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      container_name: inklinker_frontend_container
      env_file:
        - .env
      networks:
        - inklinker_network

  redis:
    image: redis
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - inklinker_network
    depends_on:
      - inklinker_backend

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./private/mergedCert.crt:/etc/ssl/certs/mergedCert.crt
      - ./private/private.key:/etc/ssl/certs/private.key
    networks:
      - inklinker_network
    depends_on:
      - inklinker_backend

volumes:
  model_data:

networks:
  inklinker_network:   
