version: '3.8'

services:

  inkLinker_backend:
      build: 
        context: ./backend
        dockerfile: Dockerfile
      container_name: inkLinker_backend_container
      env_file:
        - .env
      networks:
        - inkLinker_network

  inkLinker_frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      container_name: inkLinker_frontend_container
      env_file:
        - .env
      networks:
        - inkLinker_network

  redis:
    image: redis
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - inkLinker_network
# /certs?
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./private/mergedCert.crt:/etc/ssl/mergedCert.crt
      - ./private/private.key:/etc/ssl/private.key
    networks:
      - inkLinker_network
    depends_on:
      - inkLinker_backend


networks:
  inkLinker_network:   
